name: HTML Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Create lint script
        run: |
          echo '#!/bin/bash
          exit_code=0
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Checking $file..."
              if htmlhint "$file"; then
                echo "✓ $file passed"
              else
                echo "✗ $file failed"
                exit_code=1
              fi
            fi
          done
          exit $exit_code' > lint.sh
          chmod +x lint.sh

      - name: Run HTMLHint
        run: ./lint.sh
