name: HTML Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint
        working-directory: TrackHub
        run: |
          echo "Checking HTML files..."
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Checking $file..."
              if ! htmlhint "$file"; then
                echo "Error in $file"
                exit 1
              fi
            fi
          done
          echo "All HTML files passed linting!"
